### ISSUE TITLE
Works perfectly with 8.1.6

### ISSUE THREAD

**Issue by Xdabier** [soleverlee/db-schema-key-generator#4]
![image](https://user-images.githubusercontent.com/20482799/58751821-f6fbb880-849b-11e9-82cd-33274d43e343.png)

**Comment by GiaCatKhongVinh** [comment]
Many thanks to @soleverlee. Fits well for 8.2.10 also. Upgrading to 8.2.11 now.
![image](https://user-images.githubusercontent.com/56330908/85258171-33c49400-b491-11ea-86b1-613a9a021162.png)
